
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '8EACB126D710EDCFFB9D249EEEA3B54E'
    
_lr_action_items = {'AND':([3,4,13,14,15,16,],[-5,6,-1,-2,-3,-4,]),'OR':([3,4,13,14,15,16,],[-5,7,-1,-2,-3,-4,]),'LBRACKET':([0,2,5,6,7,8,],[2,2,2,2,2,2,]),'NOT':([2,],[5,]),'VARIABLE':([0,2,5,6,7,8,],[3,3,3,3,3,3,]),'RBRACKET':([3,9,10,11,12,13,14,15,16,],[-5,13,14,15,16,-1,-2,-3,-4,]),'IMPLICATION':([3,4,13,14,15,16,],[-5,8,-1,-2,-3,-4,]),'$end':([1,3,13,14,15,16,],[0,-5,-1,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'pred':([0,2,5,6,7,8,],[1,4,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pred","S'",1,None,None,None),
  ('pred -> LBRACKET NOT pred RBRACKET','pred',4,'p_pred_NOT','new_Homework.py',45),
  ('pred -> LBRACKET pred AND pred RBRACKET','pred',5,'p_pred_AND','new_Homework.py',49),
  ('pred -> LBRACKET pred OR pred RBRACKET','pred',5,'p_pred_OR','new_Homework.py',53),
  ('pred -> LBRACKET pred IMPLICATION pred RBRACKET','pred',5,'p_pred_IMPLICATION','new_Homework.py',57),
  ('pred -> VARIABLE','pred',1,'p_pred_terminal','new_Homework.py',61),
]
